services:
  talki-backend:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        LIVEKIT_API_KEY: ${LIVEKIT_API_KEY}
        LIVEKIT_API_SECRET: ${LIVEKIT_API_SECRET}
        LIVEKIT_SERVER_URL: ${LIVEKIT_SERVER_URL}
        API_URL: ${API_URL}
        TURSO_DATABASE_URL: ${TURSO_DATABASE_URL}
        TURSO_AUTH_TOKEN: ${TURSO_AUTH_TOKEN}
        DATABASE_URL: ${DATABASE_URL}
        PORT: 4000
        ORIGIN_CORS: ${ORIGIN_CORS}
    image: talki-backend
    environment:
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - LIVEKIT_SERVER_URL=${LIVEKIT_SERVER_URL}
      - API_URL=${API_URL}
      - TURSO_DATABASE_URL=${TURSO_DATABASE_URL}
      - TURSO_AUTH_TOKEN=${TURSO_AUTH_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - PORT=4000
      - ORIGIN_CORS=${ORIGIN_CORS}
